<?php
/*******************************************************************************
            __          __       _____   _   _  _____  _   _   _____
            \ \        / //\    |  __ \ | \ | ||_   _|| \ | | / ____|
             \ \  /\  / //  \   | |__) ||  \| |  | |  |  \| || |  __
              \ \/  \/ // /\ \  |  _  / | . ` |  | |  | . ` || | |_ |
               \  /\  // ____ \ | | \ \ | |\  | _| |_ | |\  || |__| |
                \/  \//_/    \_\|_|  \_\|_| \_||_____||_| \_| \_____|

The wp-config.php file is automatically generated by Flywheel. You will not be
able to edit this file yourself. If you need some defines added, please contact
Flywheel support at help@getflywheel.com.
*******************************************************************************/

define('FLYWHEEL_PLUGIN_DIR', dirname(__FILE__) . '/flywheel-config/plugins');
define('WPMU_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/mu-plugins');
define('WPMU_PLUGIN_URL', '/wp-content/mu-plugins');
define('FS_METHOD', 'direct');
define('WP_POST_REVISIONS',  10);


define('DB_NAME', 'db1013912022');
define('DB_USER', 'fw8745818995');
define('DB_PASSWORD', 'swKDHOXmGulA34ndQGvVrXI4LyMxdo');
define('DB_HOST', '127.0.0.1');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');




// WordPress salts
define('AUTH_KEY',          'RZn4_}1^(Ej&!Om:nIDp)-3b(idp|CP(>>4)eradE4i=k%c0,d[$`DmTMc4t)YB#');
define('SECURE_AUTH_KEY',   'YS[h|G3.ul;KHH0mYOCmz&Aw5.jE([mzS^L6Rx|RSJXS2]Kd*f+~g);/Iu0@{>&r');
define('LOGGED_IN_KEY',     '1z>LTlV]>i^asq4,[jXra@XU&%=rYGOGfP4Z@/_>D-ODiJx8Oq_m4Cnej0+RoV8u');
define('NONCE_KEY',         'h/+n[c:)2HMIHon+?vkUe3pO5M*MwL,q%tOT>2K[~dYB#BQ.9D2^f%`]7dSZV.2a');
define('AUTH_SALT',         'Blw%k*o>[padc|t@C@5>Wx5,?uuc9EY+2v2w/;Jrc<7]WSyC9kaW:u@Xqv1~bov_');
define('SECURE_AUTH_SALT',  '(@ZI%){XxyC[&yVHh[&[XhS,bOm&Z(Ox|0n,G-1j18L,vq)b/h-0z5*0xBgS6_Qe');
define('LOGGED_IN_SALT',    '^@#DcKFn37trNb-qi@)pzlMXDOJNz2%V,Q2!){1-SMK9l)sgN;&_qaKBM|Ge/|8N');
define('NONCE_SALT',        '@x&z;&{D<{KSuFh2;)!E+JxQ/%0{/-%ztJ4d.A?*rQfTh]k59qh%@)udWY<IG+lz');

$table_prefix  = 'wp_5hcm9oeosb_';

define('WPLANG', '');
define('WP_DEBUG', false);
define('WP_CACHE', false);

// Disabled WordPress core auto-updates
// http://getflywheel.com/flywheel-wordpress-3-7/
define('WP_AUTO_UPDATE_CORE', false);

if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

if ( array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' )
	$_SERVER['HTTPS']='on';

require_once(ABSPATH . 'wp-settings.php');
